name: Envoi Quotidien Maths

on:
  schedule:
    # '0 17 * * 1-5' signifie : 
    # 0: à la 0ème minute de l'heure
    # 17: à la 17ème heure (17h00 UTC = 18h00 en France en hiver)
    # *: tous les jours du mois
    # *: tous les mois
    # 1-5: du Lundi (1) au Vendredi (5)
    - cron: '0 17 * * 1-5' 
  workflow_dispatch:

jobs:
  run-math-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install requests

      - name: Lancer le script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python daily_math.py
